config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    }

  namespace :admin do
    get 'dashboard/home'
    root "dashboard#home"
    resources :experts, :users, :dissertations, :noms, :books, :journals
    resource :site
  end

  get 'home/index'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dissertation.rb
class Dissertation < ApplicationRecord
  belongs_to :language
end

app/models/expert.rb
class Expert < ApplicationRecord
  validates :name, :sex, :nation, :occupation, presence: true
  has_one_attached :avatar
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/site.rb
class Site < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/admin/noms_controller.rb
class Admin::NomsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  def index
    @page_title = t(".all_ancient_books")
  end
end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < ApplicationController
  layout "admin"
  before_action :authenticate_user!

  def show
    @page_title = "站点"
    @site = Site.first
  end
  
  def edit
    @page_title = "编辑站点"
    @site = Site.first
  end
  
  def update
    @site =  Site.first
    respond_to do |format|
      if @site.update(site_params)
        format.html {redirect_to admin_site_url, notice: "数据更新成功！"}
      else
        format.html { render :edit, status: :unprocessable_entity}
      end
    end
  end
  
  private
  def site_params
    params.require(:site).permit(:name, :slogan, :about)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "reader"
  def index
    @page_title = "首页"
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/experts_helper.rb
module Admin::ExpertsHelper
end

app/helpers/admin/journals_helper.rb
module Admin::JournalsHelper
end

app/helpers/admin/noms_helper.rb
module Admin::NomsHelper
end

app/helpers/admin/sites_helper.rb
module Admin::SitesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title> <%= @page_title||"untitled" %> | NOMINSANG 3</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "admin", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  <%= render "layouts/admin/shared/navbar" %>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <%= render "layouts/admin/shared/sidebar" %>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <%= yield %>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <%= render "layouts/admin/shared/control" %>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <%= render "layouts/admin/shared/footer" %>
</div>
<!-- ./wrapper -->
</body>
</html>

app/views/layouts/admin/shared/_control.html.erb
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <h5>Title</h5>
      <p>Sidebar content</p>
    </div>
  </aside>

app/views/layouts/admin/shared/_footer.html.erb
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      基于 <%= link_to "NOMINSANG", url_for("https://nominsang.cn") %> 构建
    </div>
    <!-- Default to the left -->
    <strong>&copy; <%= Date.today.year %> <%=link_to Site.first.name, root_path %></strong>
  </footer>

app/views/layouts/admin/shared/_navbar.html.erb
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="<%= admin_root_path %>" class="nav-link"><%= t("home") %></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <%= image_tag "user1-128x128.jpg", class: "img-size-50 mr-3 img-circle" %>
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <%= image_tag "user8-128x128.jpg", class: "img-size-50 mr-3 img-circle" %>
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <%= image_tag "user3-128x128.jpg", class: "img-size-50 mr-3 img-circle" %>
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <%=link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "dropdown-item dropdown-footer" %>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

app/views/layouts/admin/shared/_sidebar.html.erb
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="<%= admin_root_path %>" class="brand-link">
      <%= image_tag "AdminLTELogo.png", class: "brand-image img-circle elevation-3", style: "opacity: .8"%>
      <span class="brand-text font-weight-light">NOMINSANG 3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <%= image_tag "user2-160x160.jpg", class: "img-circle elevation-2" %>
        </div>
        <div class="info">
          <a href="<%= admin_user_path(current_user) %>" class="d-block"><%= current_user.email %></a>
        </div>
      </div>

      <!-- SidebarSearch Form 
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>-->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="<%= admin_root_path %>" class="nav-link<% if controller.controller_name == "dashboard" %> active<% end %>">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                <%= t(".dashboard") %>
              </p>
            </a>
          </li>
          <li class="nav-item<% if ["experts", "books", "dissertations", "noms", "journals"].include?(controller.controller_name) %> menu-open<% end %>">
            <a href="#" class="nav-link<% if ["experts", "books", "dissertations", "noms", "journals"].include?(controller.controller_name) %> active<% end %>">
              <i class="nav-icon fas fa-th"></i>
              <p>
                <%= t(".data") %>
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="<%= admin_experts_path %>" class="nav-link<% if controller.controller_name == "experts" %> active<% end %>">
                  <i class="nav-icon fa-solid fa-chalkboard-user"></i>
                  <p><%= t(".experts") %></p>
                  <span class="right badge badge-danger">New</span>
                </a>
              </li>
              <li class="nav-item">
                <a href="<%= admin_dissertations_path %>" class="nav-link<% if controller.controller_name == "dissertations" %> active<% end %>">
                  <i class="fa-solid fa-graduation-cap nav-icon"></i>
                  <p><%= t(".dissertations") %></p>
                </a>
              </li>
              <li class="nav-item">
                <a href="<%= admin_journals_path %>" class="nav-link<% if controller.controller_name == "journals" %> active<% end %>">
                  <i class="fa-solid fa-photo-film nav-icon"></i>
                  <p><%= t(".journals") %></p>
                </a>
              </li>
              <li class="nav-item">
                <a href="<%= admin_books_path %>" class="nav-link<% if controller.controller_name == "books" %> active<% end %>">
                  <i class="fa-solid fa-book nav-icon"></i>
                  <p><%= t(".books") %></p>
                </a>
              </li>
              <li class="nav-item">
                <a href="<%= admin_noms_path %>" class="nav-link<% if controller.controller_name == "noms" %> active<% end %>">
                  <i class="fa-solid fa-book-journal-whills nav-icon"></i>
                  <p><%= t(".ancient_books") %></p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="<%= admin_users_path %>" class="nav-link<%= " active" if controller.controller_name == "users" %>">
              <i class="nav-icon fa-solid fa-users"></i>
              <p>
                <%= t(".users") %>
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="<%= admin_site_path %>" class="nav-link<%= " active" if controller.controller_name == "sites" %>">
              <i class="nav-icon fa-solid fa-sitemap"></i>
              <p>
                <%= t(".site") %>
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nominsang</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/reader.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title><%= @page_title||"未命名" %> - NOMINSANG</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "reader", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <script src="https://kit.fontawesome.com/2828f7885a.js"
    integrity="sha384-WAsFbnLEQcpCk8lM1UTWesAf5rGTCvb2Y+8LvyjAAcxK1c3s5c0L+SYOgxvc6PWG"
    crossorigin="anonymous"></script>
  <link rel="icon" type="image/png" href="favicon.png" />
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap" rel="stylesheet" />
</head>

<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="container">
      <div class="navbar-brand">
        <a class="navbar-item" href="https://bulma.io">
          <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28" />
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-end">
          <a class="navbar-item"> <%= t("literatures") %> </a>
          <a class="navbar-item"> <%= t("authors") %> </a>
          <a class="navbar-item"> <%= t("about") %> </a>
        </div>
      </div>
    </div>
  </nav>
  <section class="hero is-medium">
    <div class="hero-body has-text-centered">
      <h1 class="title is-2">Books, Journals, and Papers...</h1>
      <div id="hero-input-group" class="field has-addons has-addons-centered">
        <div class="control">
          <input class="input is-medium" type="text" placeholder="Search..." />
        </div>
        <div class="control">
          <a class="button is-medium is-primary">

            <i class="fal fa-search"></i>

          </a>
        </div>
      </div>
    </div>
  </section>
  <div class="container is-max-desktop">
    <section class="featured">
      <div class="level">
        <div class="level-left">
          <div class="level-item">
            <h2 class="subtitle">Featured Articles</h2>
          </div>
        </div>
        <div class="level-right">
          <div class="level-item">
            <div class="field has-addons has-addons-centered">
              <div class="control">
                <a class="button is-small" disabled>
                  <i class="far fa-chevron-left"></i>
                </a>
              </div>
              <div class="control">
                <a class="button is-small">
                  <i class="far fa-chevron-right"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="columns">
        <div class="column is-3">
          <article>
            <figure class="image is-5by3">
              <%= image_tag "bg.jpg" %>
            </figure>
            <h2 class="subtitle">Creating a Group</h2>
            <span class="tag is-rounded">Users & Groups</span>
          </article>
        </div>
        <div class="column is-3">
          <article>
            <figure class="image is-5by3">
              <img src="https://i.ibb.co/fq8hSGQ/placeholder-image-368x246.png" />
            </figure>
            <h2 class="subtitle">Downloading/Printing Your Invoices</h2>
            <span class="tag is-rounded">Billing & Accounts</span>
          </article>
        </div>
        <div class="column is-3">
          <article>
            <figure class="image is-5by3">
              <img src="https://i.ibb.co/fq8hSGQ/placeholder-image-368x246.png" />
            </figure>
            <h2 class="subtitle">Changing the Account Owner</h2>
            <span class="tag is-rounded">Billing & Accounts</span>
          </article>
        </div>
        <div class="column is-3">
          <article>
            <figure class="image is-5by3">
              <img src="https://i.ibb.co/fq8hSGQ/placeholder-image-368x246.png" />
            </figure>
            <h2 class="subtitle">Adding Internal Notes</h2>
            <span class="tag is-rounded">Billing & Accounts</span>
          </article>
        </div>
      </div>
    </section>
    <section class="categories">
      <div class="columns is-multiline">
        <div class="column is-6">
          <div class="category">
            <h1 class="title is-5">
              Billing & Accounts <span>5 articles</span>
            </h1>
            <hr />
            <ul>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                General Billing Overview
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Changing the Account Owner
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Downloading/Printing Your Invoices
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Downloading/Printing Your Invoices
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                What to Do When Your Card is Declined
              </li>
            </ul>
            <h3 class="category-more">View All <i class="far fa-arrow-right icon-padding-left"></i></h3>
          </div>
        </div>
        <div class="column is-6">
          <div class="category">
            <h1 class="title is-5">
              FAQs <span>7 articles</span>
            </h1>
            <hr />
            <ul>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Why Isn't My Custom Profile Data Showing on My Tickets?
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Why Won't My Gmail SMTP Settings Work?
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Is There a Customer Portal My Users Can Log in To?
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                How Do I Export My Contacts, Tickets, Reports?
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                How Do I Search for a Number?
              </li>
            </ul>
            <h3 class="category-more">View All <i class="far fa-arrow-right icon-padding-left"></i></h3>
          </div>
        </div>
        <div class="column is-6">
          <div class="category">
            <h1 class="title is-5">
              Getting Started <span>6 articles</span>
            </h1>
            <hr />
            <ul>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Creating a New Conversation
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Assigning Conversations and Changing Status
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Adding Internal Notes
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Configuring Your Inbox View
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Snoozing a Conversation
              </li>
            </ul>
            <h3 class="category-more">View All <i class="far fa-arrow-right icon-padding-left"></i></h3>
          </div>
        </div>
        <div class="column is-6">
          <div class="category">
            <h1 class="title is-5">
              Users & Groups <span>3 articles</span>
            </h1>
            <hr />
            <ul>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Understanding User Roles
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Creating a Group
              </li>
              <li>
                <i class="fas fa-caret-right fa-xs icon-padding-right" /></i>
                Editing the Role of a User
              </li>
            </ul>
            <h3 class="category-more">View All <i class="far fa-arrow-right icon-padding-left"></i></h3>
          </div>
        </div>
      </div>
    </section>
  </div>
  <footer class="footer">
    <div class="container">
      <div class="content has-text-centered">
        <div class="links">

          <div class="level-item">
            <a href="#">Link One</a>
          </div>
          <div class="level-item">
            <a href="#">Link One</a>
          </div>
          <div class="level-item">
            <a href="#">Link One</a>
          </div>
        </div><br>
        <p>
          <a href="https://bulma.io">
            <img src="https://bulma.io/images/made-with-bulma.png" alt="Made with Bulma" width="128" height="24">
          </a>
        </p>
      </div>
    </div>
  </footer>
  <script>
    // Hamburger menu functionality
    document.addEventListener('DOMContentLoaded', () => {
      const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
      if ($navbarBurgers.length > 0) {
        $navbarBurgers.forEach(el => {
          el.addEventListener('click', () => {
            const target = el.dataset.target;
            const $target = document.getElementById(target);
            el.classList.toggle('is-active');
            $target.classList.toggle('is-active');
          });
        });
      }
    });
  </script>
</body>

</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login - NOMINSANG 3</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet"> -->
    <link href="https://fonts.googleapis.com/css?family=Questrial&display=swap" rel="stylesheet">
    <!-- Bulma Version 0.9.0-->
    <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.0/css/bulma.min.css" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "user", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <section class="hero is-success is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="column is-4 is-offset-4">
                  <%= yield %>
                </div>
            </div>
        </div>
    </section>
    <script async type="text/javascript" src="../js/bulma.js"></script>
</body>

</html>