config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    }

  namespace :admin do
    get 'dashboard/home'
    root "dashboard#home"
    resources :experts, :users, :dissertations, :noms, :books, :journals
    resource :site
  end

  get 'home/index'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dissertation.rb
class Dissertation < ApplicationRecord
  belongs_to :language
end

app/models/expert.rb
class Expert < ApplicationRecord
  validates :name, :sex, :nation, :occupation, presence: true
  has_one_attached :avatar
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/site.rb
class Site < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/admin/dissertations_controller.rb
class Admin::DissertationsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  before_action :set_dissertation, only: %i[show edit update destroy]
  
  def index
    @page_title = t(".all_dissertations")
    @dissertations = Dissertation.all
  end
  
  def show
  end

  def new
    @page_title = t(".new_dissertation")
    @dissertation = Dissertation.new
  end
  
  def create
    @dissertation = Dissertation.new(dissertation_params)
    respond_to do |format|
      if @dissertation.save
        format.html {redirect_to admin_dissertation_url(@dissertation), notice: t("dissertation_was_successfully_saved")}
      else
        format.html {render :new, status: :unprocessable_entity}
      end
    end
  end
  
  def edit
    
  end

  def update
    respond_to do |format|
      if @dissertation.update(dissertation_params)
        format.html { redirect_to admin_dissertation_rul(@dissertation), notice: t("dissertation_was_successfuly_updated")}
      else
        format.html {render :edit, status: :unprocessable_entity}
      end
    end
  end
  
  def destroy
    @dissertation.destroy
    
    respond_to do |format|
      format.html{redirect_to admin_dissertations_url, status: :see_other, notice: "dissertation_was_successfully_destroied"}
    end
  end
  
  private
  
  def dissertation_params
    params.require(:dissertation).permit(:title, :subtitle, :author, :teacher, :abstract, :language)
  end

  def set_dissertation
    @dissertation = Dissertation.find(params[:id])
  end
end

app/controllers/admin/noms_controller.rb
class Admin::NomsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  def index
    @page_title = t(".all_ancient_books")
  end
end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < ApplicationController
  layout "admin"
  before_action :authenticate_user!

  def show
    @page_title = "站点"
    @site = Site.first
  end
  
  def edit
    @page_title = "编辑站点"
    @site = Site.first
  end
  
  def update
    @site =  Site.first
    respond_to do |format|
      if @site.update(site_params)
        format.html {redirect_to admin_site_url, notice: "数据更新成功！"}
      else
        format.html { render :edit, status: :unprocessable_entity}
      end
    end
  end
  
  private
  def site_params
    params.require(:site).permit(:name, :slogan, :about)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  
  def index
    @page_title = "全部用户"
    @users = User.all
  end
  
  def show
    @page_title = "用户信息"
    @user =  User.find(params[:id])
  end
  
  def new
    @page_title = "新增用户"
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html {redirect_to [:admin, @user], notice: "用户成功创建！"}
      else
        format.html {render :new, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @page_title = "编辑用户"
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to admin_users_url, notice: "用户信息更新成功！"}
      else
        format.html {render :edit, status: :unprocessabel_entiry }
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html {redirect_to admin_users_url, status: see_other, notice: "该用户已经被删除！"}
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "reader"
  def index
    @page_title = "首页"
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/dissertations_helper.rb
module Admin::DissertationsHelper
end

app/helpers/admin/experts_helper.rb
module Admin::ExpertsHelper
end

app/helpers/admin/journals_helper.rb
module Admin::JournalsHelper
end

app/helpers/admin/noms_helper.rb
module Admin::NomsHelper
end

app/helpers/admin/sites_helper.rb
module Admin::SitesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/dissertations/_form.html.erb
              <%= form_with(model: [:admin, dissertation]) do |form| %>
                <div class="card-body">
                  <div class="form-group">
                    <%= form.label :title %>
                    <%= form.text_field :title, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :subtitle %>
                    <%= form.text_field :subtitle, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :author %>
                    <%= form.text_field :author, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :teacher %>
                    <%= form.text_field :teacher, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :language_id %>
                    <%= form.text_field :language_id, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :student_id %>
                    <%= form.text_field :student_id, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :department %>
                    <%= form.text_field :department, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :discipline %>
                    <%= form.text_field :discipline, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :subject %>
                    <%= form.text_field :subject, class: "form-control" %>
                  </div>
                  <div class="form-group">
                    <%= form.label :abstract %>
                    <%= form.text_area :abstract, class: "form-control", rows: 6 %>
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <%= form.submit class: "btn btn-primary" %>
                </div>
              <% end %>

app/views/admin/dissertations/index.html.erb
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><%= t(".dissertations") %></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<%= admin_root_path %>"><%= t("home") %></a></li>
              <li class="breadcrumb-item active"><%= t(".dissertations") %></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title"><%= t(".dissertations_list") %></h3>

          <div class="card-tools">
            <%= link_to t(".new_dissertation"), new_admin_dissertation_path %>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          ID
                      </th>
                      <th style="width: 20%">
                          <%= t(".email") %>
                      </th>
                      <th style="width: 30%">
                          <%= t(".password") %>
                      </th>
                      <th>
                          <%= t(".name") %>
                      </th>
                      <th style="width: 8%" class="text-center">
                          <%= t("created_at") %>
                      </th>
                      <th style="width: 20%">
                      </th>
                  </tr>
              </thead>
              <tbody>
                  <% @dissertations.each do |dissertation| %>
                  <tr>
                      <td>
                          <%= dissertation.id %>
                      </td>
                      <td>
                          <a>
                              <%= dissertation.title %>
                          </a>
                      </td>
                      <td>

                      </td>
                      <td class="project_progress">

                      </td>
                      <td class="project-state">
                          <%= dissertation.created_at %>
                      </td>
                      <td class="project-actions text-right">
                          <a class="btn btn-primary btn-sm" href="<%= admin_dissertation_path(dissertation) %>">
                              <i class="fas fa-eye">
                              </i>
                          </a>
                          <a class="btn btn-info btn-sm" href="<%= edit_admin_dissertation_path(dissertation) %>">
                              <i class="fas fa-pencil-alt">
                              </i>
                          </a>
                          <%= link_to '<i class="fas fa-trash"></i>'.html_safe, [:admin, dissertation], data: { turbo_method: :delete, turbo_confirm: "您确认删除该信息吗？" }, class: "btn btn-danger btn-sm" %>
                      </td>
                  </tr>
                  <% end %>
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>

app/views/admin/dissertations/new.html.erb
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><%= t(".new_dissertation") %></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><%= link_to t("home"), admin_root_path %></li>
              <li class="breadcrumb-item"><%=link_to t(".dissertation"), admin_dissertations_path %></li>
              <li class="breadcrumb-item active"><%= t(".new_dissertation") %></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title"><%= t(".dissertation_information") %></h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <%= render "form", dissertation: @dissertation %>
            </div>
            <!-- /.card -->

          </div>
          <!--/.col (left) -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>