config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    }

  namespace :admin do
    get 'dashboard/home'
    root "dashboard#home"
    resources :experts, :users, :dissertations, :noms, :books, :journals
    resource :site
  end

  get 'home/index'
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/dissertation.rb
class Dissertation < ApplicationRecord
  belongs_to :language
end

app/models/expert.rb
class Expert < ApplicationRecord
  validates :name, :sex, :nation, :occupation, presence: true
  has_one_attached :avatar
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/site.rb
class Site < ApplicationRecord
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  
  def index
  end
end

app/controllers/admin/experts_controller.rb
class Admin::ExpertsController < ApplicationController
  before_action :authenticate_user!
  layout "admin"
  def index
    @page_title = "专家学者"
    @experts = Expert.all
  end
  
  def show
    @page_title = "专家信息"
    @expert = Expert.find(params[:id])
  end
  
  def new
    @page_title = "新增专家学者"
    @expert = Expert.new
  end
  
  def create
    @expert = Expert.new(expert_params)
    respond_to do |format|
      if @expert.save
        format.html {redirect_to [:admin, @expert], notice: "专家信息已保存！"}
      else
        format.html {render :new, status: :unprocessable_entity}
      end
    end
  end
  
  def edit
    @page_title = "编辑专家信息"
    @expert = Expert.find(params[:id])
  end
  
  def update
    @expert = Expert.find(params[:id])
    respond_to do |format|
      if @expert.update(expert_params)
        format.html {redirect_to admin_expert_url(@expert), notice: "专家信息已更新！"}
      else
        format.html {render :edit, status: :unprocessable_entity}
      end
    end
  end
  
  def destroy
    @expert =  Expert.find(params[:id])
    @expert.destroy
    respond_to do |format|
      format.html {redirect_to admin_experts_url, status: :see_other, notice: "该专家信息已经删除！"}
    end
  end
  
  private
  def expert_params
    params.require(:expert).permit(:name, :alias_name, :sex, :nation, :birthday, :deathday, :occupation, :biographical_text, :avatar)
  end
end

app/controllers/admin/noms_controller.rb
class Admin::NomsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  def index
    @page_title = t(".all_ancient_books")
  end
end

app/controllers/admin/sites_controller.rb
class Admin::SitesController < ApplicationController
  layout "admin"
  before_action :authenticate_user!

  def show
    @page_title = "站点"
    @site = Site.first
  end
  
  def edit
    @page_title = "编辑站点"
    @site = Site.first
  end
  
  def update
    @site =  Site.first
    respond_to do |format|
      if @site.update(site_params)
        format.html {redirect_to admin_site_url, notice: "数据更新成功！"}
      else
        format.html { render :edit, status: :unprocessable_entity}
      end
    end
  end
  
  private
  def site_params
    params.require(:site).permit(:name, :slogan, :about)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  
  def index
    @page_title = "全部用户"
    @users = User.all
  end
  
  def show
    @page_title = "用户信息"
    @user =  User.find(params[:id])
  end
  
  def new
    @page_title = "新增用户"
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html {redirect_to [:admin, @user], notice: "用户成功创建！"}
      else
        format.html {render :new, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @page_title = "编辑用户"
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html {redirect_to admin_users_url, notice: "用户信息更新成功！"}
      else
        format.html {render :edit, status: :unprocessabel_entiry }
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html {redirect_to admin_users_url, status: see_other, notice: "该用户已经被删除！"}
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "reader"
  def index
    @page_title = "首页"
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/dissertations_helper.rb
module Admin::DissertationsHelper
end

app/helpers/admin/experts_helper.rb
module Admin::ExpertsHelper
end

app/helpers/admin/journals_helper.rb
module Admin::JournalsHelper
end

app/helpers/admin/noms_helper.rb
module Admin::NomsHelper
end

app/helpers/admin/sites_helper.rb
module Admin::SitesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/experts/_form.html.erb
    <section class="content">
      <%= form_with(model: [:admin, expert]) do |form| %>
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title"><%= t(".general") %></h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="card-body">

              <% if expert.errors.any? %>
                <div style="color: red">
                  <h2><%= pluralize(expert.errors.count, "error") %> prohibited this expert from being saved:</h2>

                  <ul>
                    <% expert.errors.each do |error| %>
                      <li><%= error.full_message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="form-group">
                <%= form.label :name %>
                <%= form.text_field :name, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= form.label :alias_name %>
                <%= form.text_field :alias_name, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= form.label :sex %>
                <%= form.text_field :sex, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= form.label :nation %>
                <%= form.text_field :nation, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= form.label :birthday %>
                <%= form.text_field :birthday, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= form.label :deathday %>
                <%= form.text_field :deathday, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= form.label :birthplace %>
                <%= form.text_field :birthplace, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= form.label :occupation %>
                <%= form.text_field :occupation, class: "form-control" %>
              </div>
              <div class="form-group">
                <%= form.label :biographical_text %>
                <%= form.text_area :biographical_text, class: "form-control", rows: 4 %>
              </div>

            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
        <div class="col-md-6">
          <div class="card card-secondary">
            <div class="card-header">
              <h3 class="card-title"><%= t(".avatar") %></h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="card-body">
              <div class="form-group">
              <div class="input-group">
               <div class="custom-file">
                <%= form.file_field :avatar, class: "custom-file-input" %>
                <label for="expert_avatar" class="custom-file-label">
                <% if expert.avatar.attached? %>
                <%= expert.avatar.filename %>
                <% else %>
                <%= t(".please_select_avatar") %>
                <% end %>
                </label>
              </div> 
              <div class="input-group-append">
                <span class="input-group-text"><%= t(".upload") %></span>
              </div>              
              </div>
              </div>
            </div>
            <!-- /.card-body -->
          </div>
          <!-- /.card -->
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <%= form.submit class: "btn btn-success" %>
        </div>
      </div>
      <% end %>
    </section>

app/views/admin/experts/edit.html.erb
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><%= t(".edit_expert") %></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<%= admin_root_path %>"><%= t("home") %></a></li>
              <li class="breadcrumb-item"><%=link_to t(".experts"), admin_experts_path %></li>
              <li class="breadcrumb-item active"><%= t(".edit_expert") %></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <%= render "form", expert: @expert %>

app/views/admin/experts/index.html.erb
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><%= t(".experts") %></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<%= admin_root_path %>"><%= t("home") %></a></li>
              <li class="breadcrumb-item active"><%= t(".experts") %></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title"><%= t(".experts_list") %></h3>

          <div class="card-tools">
            <%= link_to t(".new_expert"), new_admin_expert_path %>
          </div>
        </div>
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          ID
                      </th>
                      <th style="width: 20%">
                          <%= t(".name") %>
                      </th>
                      <th style="width: 30%">
                          <%= t(".nation") %>
                      </th>
                      <th>
                          <%= t(".occupation") %>
                      </th>
                      <th style="width: 8%" class="text-center">
                          <%= t("created_at") %>
                      </th>
                      <th style="width: 20%">
                      </th>
                  </tr>
              </thead>
              <tbody>
                  <% @experts.each do |expert| %>
                  <tr>
                      <td>
                          <%= expert.id %>
                      </td>
                      <td>
                          <a>
                              <%= expert.name %>
                          </a>
                      </td>
                      <td>
                          <%= expert.nation %>
                      </td>
                      <td class="project_progress">
                          <%= expert.occupation %>
                      </td>
                      <td class="project-state">
                          <%= expert.created_at %>
                      </td>
                      <td class="project-actions text-right">
                          <a class="btn btn-primary btn-sm" href="<%= admin_expert_path(expert) %>">
                              <i class="fas fa-eye">
                              </i>
                          </a>
                          <a class="btn btn-info btn-sm" href="<%= edit_admin_expert_path(expert) %>">
                              <i class="fas fa-pencil-alt">
                              </i>
                          </a>
                          <%= link_to '<i class="fas fa-trash"></i>'.html_safe, [:admin, expert], data: { turbo_method: :delete, turbo_confirm: "您确认删除该信息吗？" }, class: "btn btn-danger btn-sm" %>
                      </td>
                  </tr>
                  <% end %>
              </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>

app/views/admin/experts/new.html.erb
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><%= t(".new_expert") %></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<%= admin_root_path %>"><%= t("home") %></a></li>
              <li class="breadcrumb-item"><%=link_to t(".experts"), admin_experts_path %></li>
              <li class="breadcrumb-item active"><%= t(".new_expert") %></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>
    <%= render "form", expert: @expert %>

app/views/admin/experts/show.html.erb
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1><%= t(".expert_information") %></h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<%= admin_root_path %>"><%= t("home") %></a></li>
              <li class="breadcrumb-item"><%= link_to t(".experts"), admin_experts_path %></li>
              <li class="breadcrumb-item active"><%= t(".expert_information") %></li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card card-solid">
        <div class="card-body">
          <div class="row">
            <div class="col-12 col-sm-6">
              <h3 class="d-inline-block d-sm-none"><%= @expert.name %></h3>
              <div class="col-12">
                <% if @expert.avatar.attached? %>
               <%= image_tag @expert.avatar, class: "product-image" %>
                <% end %>
              </div>
            </div>
            <div class="col-12 col-sm-6">
              <h3 class="my-3"><%= @expert.name %></h3>
              <% if @expert.alias_name %>
              <p><%= t(".alias_name") %> <%= @expert.alias_name %></p>
              <% end %>
              <hr>
              <h4>Available Colors</h4>
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-default text-center active">
                  <input type="radio" name="color_option" id="color_option_a1" autocomplete="off" checked="">
                  Green
                  <br>
                  <i class="fas fa-circle fa-2x text-green"></i>
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_a2" autocomplete="off">
                  Blue
                  <br>
                  <i class="fas fa-circle fa-2x text-blue"></i>
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_a3" autocomplete="off">
                  Purple
                  <br>
                  <i class="fas fa-circle fa-2x text-purple"></i>
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_a4" autocomplete="off">
                  Red
                  <br>
                  <i class="fas fa-circle fa-2x text-red"></i>
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_a5" autocomplete="off">
                  Orange
                  <br>
                  <i class="fas fa-circle fa-2x text-orange"></i>
                </label>
              </div>

              <h4 class="mt-3">Size <small>Please select one</small></h4>
              <div class="btn-group btn-group-toggle" data-toggle="buttons">
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_b1" autocomplete="off">
                  <span class="text-xl">S</span>
                  <br>
                  Small
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_b2" autocomplete="off">
                  <span class="text-xl">M</span>
                  <br>
                  Medium
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_b3" autocomplete="off">
                  <span class="text-xl">L</span>
                  <br>
                  Large
                </label>
                <label class="btn btn-default text-center">
                  <input type="radio" name="color_option" id="color_option_b4" autocomplete="off">
                  <span class="text-xl">XL</span>
                  <br>
                  Xtra-Large
                </label>
              </div>

              <div class="bg-gray py-2 px-3 mt-4">
                <h2 class="mb-0">
                  <%= t(".date_of_birth_and_death") %>
                </h2>
                <h4 class="mt-0">
                  <small><%= @expert.birthday %> - <%= @expert.deathday %> </small>
                </h4>
              </div>

              <div class="mt-4">
                <a href="<%= edit_admin_expert_path(@expert) %>" class="btn btn-primary btn-lg btn-flat">
                  <i class="fas fa-cart-plus fa-lg mr-2"></i>
                  
                  <%= t(".edit_expert_information") %>
                  
                </a>

                <div class="btn btn-default btn-lg btn-flat">
                  <i class="fas fa-heart fa-lg mr-2"></i>
                  <%= t(".delete_expert_information") %>
                </div>
              </div>

            </div>
          </div>
          <div class="row mt-4">
            <nav class="w-100">
              <div class="nav nav-tabs" id="product-tab" role="tablist">
                <a class="nav-item nav-link active" id="product-desc-tab" data-toggle="tab" href="#product-desc" role="tab" aria-controls="product-desc" aria-selected="true"><%= t(".biographical_text") %></a>
                <a class="nav-item nav-link" id="product-comments-tab" data-toggle="tab" href="#product-comments" role="tab" aria-controls="product-comments" aria-selected="false">Comments</a>
                <a class="nav-item nav-link" id="product-rating-tab" data-toggle="tab" href="#product-rating" role="tab" aria-controls="product-rating" aria-selected="false">Rating</a>
              </div>
            </nav>
            <div class="tab-content p-3" id="nav-tabContent">
              <div class="tab-pane fade show active" id="product-desc" role="tabpanel" aria-labelledby="product-desc-tab">
                <%= @expert.biographical_text %>
              </div>
              <div class="tab-pane fade" id="product-comments" role="tabpanel" aria-labelledby="product-comments-tab"> Vivamus rhoncus nisl sed venenatis luctus. Sed condimentum risus ut tortor feugiat laoreet. Suspendisse potenti. Donec et finibus sem, ut commodo lectus. Cras eget neque dignissim, placerat orci interdum, venenatis odio. Nulla turpis elit, consequat eu eros ac, consectetur fringilla urna. Duis gravida ex pulvinar mauris ornare, eget porttitor enim vulputate. Mauris hendrerit, massa nec aliquam cursus, ex elit euismod lorem, vehicula rhoncus nisl dui sit amet eros. Nulla turpis lorem, dignissim a sapien eget, ultrices venenatis dolor. Curabitur vel turpis at magna elementum hendrerit vel id dui. Curabitur a ex ullamcorper, ornare velit vel, tincidunt ipsum. </div>
              <div class="tab-pane fade" id="product-rating" role="tabpanel" aria-labelledby="product-rating-tab"> Cras ut ipsum ornare, aliquam ipsum non, posuere elit. In hac habitasse platea dictumst. Aenean elementum leo augue, id fermentum risus efficitur vel. Nulla iaculis malesuada scelerisque. Praesent vel ipsum felis. Ut molestie, purus aliquam placerat sollicitudin, mi ligula euismod neque, non bibendum nibh neque et erat. Etiam dignissim aliquam ligula, aliquet feugiat nibh rhoncus ut. Aliquam efficitur lacinia lacinia. Morbi ac molestie lectus, vitae hendrerit nisl. Nullam metus odio, malesuada in vehicula at, consectetur nec justo. Quisque suscipit odio velit, at accumsan urna vestibulum a. Proin dictum, urna ut varius consectetur, sapien justo porta lectus, at mollis nisi orci et nulla. Donec pellentesque tortor vel nisl commodo ullamcorper. Donec varius massa at semper posuere. Integer finibus orci vitae vehicula placerat. </div>
            </div>
          </div>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>